{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dynamic-analysis-agent.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynamic-analysis-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- if .Values.persistence.existingClaim }}
  volumeName: {{ .Values.persistence.existingClaim }}
  {{- end }}
{{- end }}
